// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed num, find the sum of the even-valued terms.

const fiboEvenSum = num => {
  let sumOfEven = temp = prevNum = 0;
  let nextNum = 1;
    while(temp <= num) {
    temp = prevNum + nextNum;
    prevNum = nextNum;
    nextNum = temp;
    if (isEven(temp)) {
      sumOfEven += temp;
    };
  }
  return sumOfEven;
}

const isEven = num => num % 2 === 0;
